name: CI

on:
  push:
    branches: [main]
  schedule:
     - cron: '0 0 * * *'

jobs:
  docker-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y chromium-browser
          pip install selenium==4.6.0 webdriver-manager==3.8.4 packaging==21.3

      - name: Docker build
        run: |
          python docker-build.py
